services:
  crypto-price-tracker:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: pnpm run start:dev reservations
    env_file:
      - ./.env
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app